### ISSUE TITLE
PlatformIO is inconsistent on automatic dependencies search

### ISSUE THREAD

**Issue by jomarx** [idolpx/mobile-rr#17]
PIO (IDE 1.6.0 | CLI 3.1.0) is not autodetecting the dependent libraries, and causing issues. Can we just define all the required libraries on platformio.ini?

**Comment by idolpx** [comment]
It seemed to be doing ok in my tests.  That's why I removed them from the platformio.ini file but it is probably best to have them there.

**Comment by idolpx** [comment]
I merged in the changes to the platformio.ini that identify the dependencies.  This will help with those that are having issues with it finding them properly.
