### ISSUE TITLE
SSID changes not processed

### ISSUE THREAD

**Issue by petorian** [idolpx/mobile-rr#21]
When changing the SSID, the change is not applied.
It seems line 477 causes this behaviour:
`if ( config.channel != chan_selected ) // || config.ssid != ssid) )`

If I change this to `if (1==1)` then the code after that is applied and the access point is spawned with the new SSID,

If I uncomment the OR clause then I receive an error: 

> comparison between distinct pointer types 'uint8* {aka unsigned char*}' and 'char*' lacks a cast [-fpermissive] 

I do not have a lot of knowledge about changing this type, but will dive into this. Any help of course is appreciated.

**Comment by idolpx** [comment]
When I was working on the issue with changing the channel I commented that out and meant to come back and fix it.  Sorry about that.  

Check for my update.  That should do the trick.  ;)
I haven't tested it yet.  My main system is down at the moment.
Let me know if that does the trick.

**Comment by petorian** [comment]
Thanks, i'll try the update ! 👍🏼

Dennis

Op wo 22 mrt. 2017 om 00:32 schreef idolpx <notifications@github.com>

**Comment by idolpx** [comment]
Ok...  finally had some time to test things out.  
Pull these changes and you should be good.

I fixed the IP issue too that you told me about.
The default 10.10.10.1 IP should work now.

**Comment by petorian** [comment]
Great,  I really appreciate it! Thanks for fixing it.

**Comment by idolpx** [comment]
No prob.  I look forward to your feedback.  Have fun!
