### ISSUE TITLE
Broadcast SSID remains unchanged after changing variable

### ISSUE THREAD

**Issue by mikedan99** [idolpx/mobile-rr#23]
Summary: Changing the SSID variable in the @@@ section has no effect on the actual SSID used when the code is running. 

Details: In the section marked // Global data section I changed the default value to:
char ssid[]                 = "Free Hi-Speed WiFi";

However, the default SSID continues to broadcast. It doesn't matter what new value I use, the original value is broadcast.

More info: I assume that the original default SSID is hardcoded somewhere but I simply cannot find it. I've wiped and reloaded SPIFFS storage as well as searching both the storage files and source code, but I can't find where this is happening. I'm happy to help fix if anyone can point me in the right direction!

**Comment by idolpx** [comment]
On the first run the settings are stored in EEPROM and reloaded from there on boot.

If you reset the settings to default using the console interface it will use the new default SSID.  You can also change the SSID from the console interface as well and it is stored in EEPROM.
