### ISSUE TITLE
Browser Error

### ISSUE THREAD

**Issue by DanielL99** [idolpx/mobile-rr#24]
Hi, I tried the code on a Nodemcu (ESP-12e) 
Compiling and flashing works (After some attempts)
But  I always get an error Message on my Phone (Android 7):
`"Error to many redirects"` or 
`"The page isn't redirecting properly - Firefox has detected that the server is redirecting the request for this address in a way that will never complete."`

**Comment by idolpx** [comment]
This error is typically caused when there is no SPIFFS file system.
Please follow the instructions for flashing that image as well.

**Comment by DanielL99** [comment]
*facepalm*
Yes, that makes sense
Sorry, I was so happy, that I was able to flash it, that I forgot about that

**Comment by idolpx** [comment]
No worries!  Hope you have fun with it.  :)
