### ISSUE TITLE
Curiosity

### ISSUE THREAD

**Issue by treii28** [idolpx/mobile-rr#32]
I'm just wondering how  you got the mp3s so small. I was looking to see if I could condense the files down to get them to fit better on an esp-01 with a 1m chip but trying to reduce the bitrate on the mp3 files produces a bigger file. Thus I'm wondering what was used to get them so small.

**Comment by idolpx** [comment]
I don't remember the exact settings I used but it was FFMPEG.

**Comment by treii28** [comment]
hmmm, ok, thanks. That's one of the one's I tried but with rather basic settings.

**Comment by idolpx** [comment]
I do remember others using an esp-01 that just ditched the mp3 file but it does add a nice touch to the prank.  :)
