### ISSUE TITLE
'class DNSServer' has no member named 'onquery'

### ISSUE THREAD

**Issue by kodda74** [idolpx/mobile-rr#36]
Whenever I try to upload I get the error 'class DNSServer' has no member named 'onquery'. Any suggestions?

**Comment by idolpx** [comment]
Sorry so slow to reply.  It's been a while since I checked the code.  Did you get this issue figured out?

**Comment by kodda74** [comment]
No. I tried to fix it for like two weeks but I never got it fixed. Do you know what might be causing the issue? If you have a precompiled version of the code that would be awesome too

**Comment by idolpx** [comment]
I'm not having issues compiling. What OS are you using? Are you using PlatformIO in Atom or VSCode?

**Comment by kodda74** [comment]
I got it fixed this morning.  It was an issue with my PlatformIO build.

**Comment by idolpx** [comment]
Oh awesome!  :D That's good news!  Let me know what kind of fun you have with it. :)
