### ISSUE TITLE
serial.serialutil.SerialException: [Errno 2] could not open port /dev/cu.wchusbserial14440: [Errno 2] No such file or directory: '/dev/cu.wchusbserial14440'

### ISSUE THREAD

**Issue by benjaminsabella** [idolpx/mobile-rr#37]
New to all of this. Had some fun experimenting with my new ESP8266 until I stumbled upon this. I decided to try it but now im having issues. If anyone could help that would be nice

**Comment by benjaminsabella** [comment]
Additional note- It builds fine just does not upload correctly.

**Comment by idolpx** [comment]
Cool... check the settings in platformio.ini and make sure the ports are set correctly for your system.  :)

**Comment by benjaminsabella** [comment]
> Cool... check the settings in platformio.ini and make sure the ports are set correctly for your system.  :)

Thanks yeah I figured it out. Stupid mistake from me

**Comment by idolpx** [comment]
Oh good...  let me know if you have any questions or run into any probs with it.  :)
I'm happy to help.  You can get my attention faster on discord.  https://discord.gg/FwJUe8kQpS
I'm in there most of the time.
