### ISSUE TITLE
Can we still make this work?

### ISSUE THREAD

**Issue by testataaaa** [idolpx/mobile-rr#38]
As a noob I saw this project in a recent edition of Make Magazine (April 1st pranks) and through it looked well documented and straightforward.

Unfortunately I can't get this to work according to the instructions, is this still functional? If not, is there a way to do this via Arduino IDE rather than platformio?

**Comment by idolpx** [comment]
Oh awesome!  Yes!  Message me on Discord.  I'd be happy to help you get it working.
https://discord.gg/FwJUe8kQpS

**Comment by idolpx** [comment]
Hey! What issue of the magazine was it in?  I'd like to check it out.  I didn't even know about that.

**Comment by testataaaa** [comment]
Thanks for your reply, I'll check out the Discord. As reference for people stumbling upon this, it was in Make Magazine edition that came out around April, and it listed the project as a good April fool's prank.
