### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by swordapi** [idolpx/mobile-rr#40]
mobile-rr.ino:573:10: error: 'class DNSServer' has no member named 'onQuery'

**Comment by idolpx** [comment]
Are you using PlatformIO?

**Comment by swordapi** [comment]
No

**Comment by idolpx** [comment]
That is probably the problem.  Can you try it with PlatformIO and VSCode?
Let me know how that goes.

**Comment by swordapi** [comment]
I dont have this im mobile

**Comment by idolpx** [comment]
Tell me what you are using to compile the firmware and flash it to the ESP8266 module.
I might be able to help.  You haven't given me enough information yet.

**Comment by swordapi** [comment]
ArduinoDroid app

**Comment by idolpx** [comment]
Ok... I don't know anything about that.  This project was intended to be used with PlatformIO.
Please follow the instructions for getting things setup on a computer to build the firmware.

**Comment by swordapi** [comment]
Ok
